/**
 * Email Export — Doctor-Ready Clinical Summary
 *
 * Generates a professional, plain-text medical summary formatted for
 * emailing to a physician. Uses mailto: with pre-filled subject/body,
 * plus clipboard fallback.
 */

/**
 * Build a structured clinical consultation summary suitable for
 * physician-to-physician communication.
 *
 * @param {Object} params
 * @param {Array}  params.causes           - Differential diagnoses [{cause, value, urgency, specialty, explanation}]
 * @param {Array}  params.redFlags         - Red flag warnings
 * @param {Array}  params.recommendedTests - Recommended diagnostic tests
 * @param {Array}  params.medications      - Medications [{name, dose} | string]
 * @param {string} params.patientAge       - Patient age
 * @param {string} params.patientGender    - Patient gender
 * @param {string} params.chiefComplaint   - Presenting complaint
 * @param {string} params.formattedDate    - Report date string
 * @param {string} params.overallUrgency   - Urgency level (e.g. "Routine", "Urgent")
 * @param {Array}  params.safetyWarnings   - Safety/contraindication warnings
 * @param {Array}  params.actionChecklist  - Recommended action items
 * @returns {{ subject: string, body: string }}
 */
export function buildDoctorEmailSummary({
  causes = [],
  redFlags = [],
  recommendedTests = [],
  medications = [],
  patientAge = '',
  patientGender = '',
  chiefComplaint = '',
  formattedDate = '',
  overallUrgency = '',
  safetyWarnings = [],
  actionChecklist = [],
} = {}) {
  const date = formattedDate || new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })

  const topDiagnosis = causes[0]?.cause || 'Unspecified'
  const top3 = causes.slice(0, 3)

  // ── Subject line ──
  const subject = `Clinical Consultation Report \u2014 ${date} \u2014 ${topDiagnosis}`

  // ── Body ──
  const lines = []

  // Header
  lines.push('CLINICAL CONSULTATION REPORT')
  lines.push('=' .repeat(50))
  lines.push(`Date: ${date}`)
  lines.push(`Priority: ${overallUrgency || 'Not assessed'}`)
  lines.push('')

  // Patient demographics
  lines.push('PATIENT DEMOGRAPHICS')
  lines.push('-'.repeat(30))
  const demoparts = []
  if (patientAge) demoparts.push(`Age: ${patientAge}`)
  if (patientGender) demoparts.push(`Sex: ${patientGender}`)
  if (demoparts.length > 0) {
    lines.push(demoparts.join('  |  '))
  } else {
    lines.push('Not provided')
  }
  lines.push('')

  // Chief complaint
  if (chiefComplaint) {
    lines.push('CHIEF COMPLAINT')
    lines.push('-'.repeat(30))
    lines.push(chiefComplaint)
    lines.push('')
  }

  // Differential diagnoses (top 3)
  if (top3.length > 0) {
    lines.push('DIFFERENTIAL DIAGNOSES')
    lines.push('-'.repeat(30))
    top3.forEach((c, i) => {
      const confidence = c.value != null ? `${c.value}%` : 'N/A'
      const urgency = c.urgency ? ` | Urgency: ${c.urgency}` : ''
      const specialty = c.specialty ? ` | ${c.specialty}` : ''
      lines.push(`${i + 1}. ${c.cause} (Confidence: ${confidence}${urgency}${specialty})`)
      if (c.explanation) {
        lines.push(`   Reasoning: ${c.explanation}`)
      }
    })
    if (causes.length > 3) {
      lines.push(`   ... and ${causes.length - 3} additional differential(s)`)
    }
    lines.push('')
  }

  // Red flags
  if (redFlags.length > 0) {
    lines.push('RED FLAGS / WARNING SIGNS')
    lines.push('-'.repeat(30))
    redFlags.forEach(f => lines.push(`  * ${f}`))
    lines.push('')
  }

  // Recommended tests
  if (recommendedTests.length > 0) {
    lines.push('RECOMMENDED INVESTIGATIONS')
    lines.push('-'.repeat(30))
    recommendedTests.forEach(t => lines.push(`  - ${t}`))
    lines.push('')
  }

  // Medications
  if (medications.length > 0) {
    lines.push('CURRENT / SUGGESTED MEDICATIONS')
    lines.push('-'.repeat(30))
    medications.forEach(m => {
      const name = typeof m === 'string' ? m : m.name
      const dose = (m && m.dose) ? ` -- ${m.dose}` : ''
      const freq = (m && m.frequency) ? ` (${m.frequency})` : ''
      lines.push(`  - ${name}${dose}${freq}`)
    })
    lines.push('')
  }

  // Safety warnings
  if (safetyWarnings.length > 0) {
    lines.push('SAFETY ALERTS / CONTRAINDICATIONS')
    lines.push('-'.repeat(30))
    safetyWarnings.forEach(w => lines.push(`  ! ${w}`))
    lines.push('')
  }

  // Action checklist
  if (actionChecklist.length > 0) {
    lines.push('RECOMMENDED ACTIONS')
    lines.push('-'.repeat(30))
    actionChecklist.forEach((a, i) => lines.push(`  ${i + 1}. ${a}`))
    lines.push('')
  }

  // Footer
  lines.push('='.repeat(50))
  lines.push('DISCLAIMER: This report was generated by an AI clinical')
  lines.push('decision support tool (MedDiagnose AI) and is intended')
  lines.push('for informational purposes only. It does not constitute')
  lines.push('a medical diagnosis. Clinical correlation and physician')
  lines.push('judgment are required.')
  lines.push('')
  lines.push(`Generated: ${date}`)
  lines.push('Source: MedDiagnose AI Clinical Consultation')

  return {
    subject,
    body: lines.join('\n'),
  }
}

/**
 * Open a mailto: link with a pre-filled doctor email summary.
 * @param {Object} params - Same params as buildDoctorEmailSummary
 */
export function openDoctorEmail(params) {
  const { subject, body } = buildDoctorEmailSummary(params)
  const mailto = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
  window.open(mailto, '_self')
}

/**
 * Copy the doctor email summary to clipboard.
 * Returns true on success, false on failure.
 * @param {Object} params - Same params as buildDoctorEmailSummary
 * @returns {Promise<boolean>}
 */
export async function copyDoctorSummary(params) {
  const { body } = buildDoctorEmailSummary(params)
  try {
    await navigator.clipboard.writeText(body)
    return true
  } catch {
    // Fallback for older browsers
    const ta = document.createElement('textarea')
    ta.value = body
    ta.style.position = 'fixed'
    ta.style.opacity = '0'
    document.body.appendChild(ta)
    ta.select()
    document.execCommand('copy')
    document.body.removeChild(ta)
    return true
  }
}
